version: '3'
services:

  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blockchain-banking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build:
      dockerfile: Dockerfile
    container_name: server
    image: blockchain-banking
    ports:
      - "8082:8082"
    depends_on:
      - db

volumes:
  postgres_data: